### ISSUE TITLE
DBInterface Issue

### ISSUE THREAD

**Issue by bandroidx** [generalfault/stratum-mining#1]
Hi, nice work on this fork.  I am trying to use it but getting the following traceback:

Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-i686.egg/twisted/application/app.py", line 402, in startReactor
        self.config, oldstdout, oldstderr, self.profiler, reactor)
      File "/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-i686.egg/twisted/application/app.py", line 323, in runReactorWithLogging
        reactor.run()
      File "/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-i686.egg/twisted/internet/base.py", line 1192, in run
        self.mainLoop()
      File "/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-i686.egg/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-i686.egg/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(_call.args, *_call.kw)
      File "/root/stratum-mining/mining/DBInterface.py", line 80, in run_import
        d = self.bitcoinrpc.getinfo()
    exceptions.AttributeError: DBInterface instance has no attribute 'bitcoinrpc'

Also, i had to copy the conf/conf.py to stratum/config.py for it to work.  stratum seems to be looking there.

**Comment by SuBPaR42** [comment]
The format is config.py (stratum-mining/conf/config.py) -- there is a sample in there as well (/stratum-mining/conf/config_sample.py).  It is best to use that sample and then resave to config.py

**Comment by bandroidx** [comment]
ah i had made a typo it seems, i moved the config file from the stratum dir and it works, but i still get the traceback error i show above.

**Comment by bandroidx** [comment]
stratum is also not responding to my incoming test connection so i assume the traceback issue is enough to prevent things from working, let me know any info you need.

**Comment by SuBPaR42** [comment]
Sadly generalfault hasn't been as active the last few weeks as I too have traceback issues but still find everything MOSTLY functional (still finding blocks).

**Comment by bandroidx** [comment]
ah thanks for the response, any idea why my server wont accept any requests?  i checked with tcpdump and they are coming in, but even with debug log on it says absolutely nothing about the incoming request....
